steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build','-t','europe-west4-docker.pkg.dev/gcp-devops-460202/devops1/myapp:v1','.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push','europe-west4-docker.pkg.dev/gcp-devops-460202/devops1/myapp:v1']
options:
  logging: CLOUD_LOGGING_ONLY

  
  